### ISSUE TITLE
LANG not set properly for at least 16.04-Desktop

### ISSUE THREAD

**Issue by vincecima** [boxcutter/ubuntu#59] opened 2016-04-27 11:38 UTC
Previously (https://github.com/boxcutter/ubuntu/commit/ed33391e10c627379dfa1f8e9a83118d05b682fd) a script was used to set the LANG to a proper value. This stopped apps from GNOME-terminal from failing on launch. With the new single template setup, that script is no longer being run and the errors are back.

**Comment by JonasGroeger** [comment] 2016-05-14 13:20
I think it is sufficient to add `script/locale.sh` to https://github.com/boxcutter/ubuntu/blob/master/ubuntu.json#L171

**Comment by tknerr** [comment] 2016-07-11 13:58
+1 for this, i.e. #64 and #61 respectively

**Comment by annawake** [comment] 2016-08-21 19:51
Addressed by https://github.com/boxcutter/ubuntu/commit/d19fd87442a82f87da9d6894af9b52a10c680418

**Closed by annawake** 2016-08-21 19:51 UTC

**Comment by tknerr** [comment] 2016-09-30 21:20
@annawake @vincecima still can not start gnome-terminal in the v2.0.22 release of the ubuntu-desktop-16.04 basebox.

d19fd87442a82f87da9d6894af9b52a10c680418 makes the locale settable, but the issue is still present until you run `update-locale LANG=...` once.
