### ISSUE TITLE
ubuntu1510 missing from atlas

### ISSUE THREAD

**Issue by rrva** [boxcutter/ubuntu#21] opened 2015-08-14 07:55 UTC
Ubuntu 15.10 is not yet published to atlas? Would be nice if ubuntu1510 for vmware and virtualbox were up on vagrantcloud/atlas

https://atlas.hashicorp.com/boxcutter/boxes/ubuntu1510

**Comment by annawake** [comment] 2015-09-21 14:44
Duplicate of https://github.com/boxcutter/ubuntu/issues/22  It is not in atlas because we cannot build ubuntu1510.  We used to be able to build with the early daily builds, but enough changed that it no longer works.  Box has been removed from atlas.

**Closed by annawake** 2015-09-21 14:44 UTC
