### ISSUE TITLE
Can't SSH into boxcutter/ubuntu1604

### ISSUE THREAD

**Issue by jarofgreen** [boxcutter/ubuntu#82] opened 2016-10-31 15:06 UTC
Anyone else having problems with this? Seen on two host computers (and I'm pretty sure an older version of the box used to work on one of the computers).

Firstly, VM boot is really slow - around 5 mins - so Vagrant times out trying to connect (yes, I know there is a setting to increase the time out).

But then, once booted, 

     ssh -p 2222 vagrant@localhost

just times out.

On one of the machines, I was able to open a direct terminal to the box, shell in with user/pass vagrant/vagrant and run the following fine

    ssh vagrant@localhost

Which suggests SSHD is running fine but it's a networking problem. The networking settings for port forwarding in VirtualBox seem fine to me. So I'm a bit stuck .... Thanks!

**Comment by rickard-von-essen** [comment] 2016-10-31 17:19
See https://github.com/chef/bento/issues/701

**Comment by jarofgreen** [comment] 2016-10-31 17:30
So, that's saying VirtualBox 5.1.8 is broken and I should go back to 5.1.6?

I'm on V4.1.44 and V5.0.16 :-D

**Comment by rickard-von-essen** [comment] 2016-10-31 17:53
5.1.6 is the golden version that works. Check if your NIC has the cable connected.

**Comment by jarofgreen** [comment] 2016-10-31 17:57
I don't think it's my VirtualBox. Both my host boxes can run boxcutter's debian box fine, so it's something special about this ubuntu box.

**Comment by jarofgreen** [comment] 2016-10-31 17:58
Let's try and narrow this down - can you confirm that the latest version of boxcutter/ubuntu1604 works for you?

**Comment by rickard-von-essen** [comment] 2016-11-01 08:00
When a box doesn't start, the first thing you should try is enable GUI and check the console.

![screen shot 2016-11-01 at 08 56 39](https://cloud.githubusercontent.com/assets/557699/19882875/1e560416-a011-11e6-9e8e-99dbdc4573a7.png)

Obviously broken box.

Ping @annawake

**Comment by jarofgreen** [comment] 2016-11-01 08:14
I did open a console, as said in my first post. I saw the same kind of message, but for me if I leave it for 5 mins it clears and the box boots anyway. Well, it boots fine for logging in at the console, but I can't log in over SSH which is the problem. 

I suspect it's a broken box to, hence this issue, but when it's volunteers doing open source (Thanks!) I like to really check things out before reporting so as not to be a pain.

**Comment by rickard-von-essen** [comment] 2016-11-01 08:28
Sorry, I might have replied a bit too quickly, felt like the hundred issue about _"can't connect to SSH with VirtualBox"_ (reported on https://github.com/chef/bento).

**Comment by jarofgreen** [comment] 2016-11-03 09:23
Ah haa! Know I said this used to work on my laptop? Fortunately, it turns out I haven't cleared out my vagrant boxes. So I could just look and see what version I had before.  By adding: 

    config.vm.box_version = "2.0.18"

I can make this box work - on both my host machines. So it's something since this version that has broken.

**Comment by smebberson** [comment] 2016-11-03 11:11
I get this issue to, running VMware Fusion, and on VirtualBox (running Mac OS X).

**Comment by sdemura** [comment] 2016-11-04 12:07
I'm seeing this issue as well. Virtualbox on OS X.

Ubuntu 14 and CentOS work fine.

**Comment by jarofgreen** [comment] 2016-11-04 15:42
Just tried the latest version of ubuntu1604-desktop and I see this:

![screen shot 2016-11-04 at 15 26 37](https://cloud.githubusercontent.com/assets/85656/20011360/3b1f2502-a2a3-11e6-97ba-9d8dd7eaf0a1.png)

That command times out, and SSH fails. This ties in with the symptoms I saw of a very long boot and then no external network interfaces once booted.

Again, 

		config.vm.box = "boxcutter/ubuntu1604-desktop"
		config.vm.box_version = "2.0.18"

boots fine.

**Comment by antwanvdm** [comment] 2016-11-16 09:53
I've fixed this by adding the following to the VagrantFile:


    # Bugfix for "Cable connected: off"
    config.vm.provider :virtualbox do |vm|
        vm.customize [
            "modifyvm", :id,
            "--cableconnected1", "on",
        ]
    end

Solution found at: https://lists.debian.org/debian-cloud/2016/09/msg00051.html

**Comment by annawake** [comment] 2016-11-25 02:03
It looks like VirtualBox 5.1.10 includes a fix for this issue, give it a go and let everyone know how it works for you.

**Comment by blech75** [comment] 2016-11-28 16:42
FWIW, I was using VirtualBox 5.0.30 with `box-cutter/ubuntu1204` and had the same lack of networking issue, for which the "cable connected" fix worked like a charm. After upgrading VB to 5.1.10, the config fix was thankfully no longer needed.

**Comment by jarofgreen** [comment] 2016-11-30 21:13
Upgrading at least one of my VirtualBoxes would be a right pain, as it comes from Linux packages. Also, as I'm trying to write stuff for others I really don't want to have to add a big warning saying "Must be 5.1.10!".

It seems like there must be something else going on here. Older versions of the same Boxcutter boxes work fine on my machines with older VirtualBox versions. That implies something else is going on - could it be to do with the version of the software used to build the box?

**Comment by rickard-von-essen** [comment] 2016-11-30 21:21
Yes it depends on the version used for building.

**Comment by jarofgreen** [comment] 2016-11-30 21:28
In that case, when can we expect new versions of the Boxcutter boxes built using the latest version of Virtualbox? (I am unfamiliar with Boxcutter's release schedule.) I can test them on my older versions of VB and if that worked, that would be much better - the BC boxes would work on all recent versions of VirtualBox. Thanks,

**Comment by annawake** [comment] 2016-12-01 04:49
There was a box release yesterday with the 5.1.10 guest additions.

I don't know why, but so far what I've heard is that people can't use these boxes with VirtualBox 5.0.x - there is the problem you mention about ssh. The issue could be with VirtualBox or vagrant or maybe even packer, that's currently unclear.

Atlas does not support multiple versions of providers per box, so boxcutter will only build boxes with the latest 5.1.x guest additions, and we hope that there is some solution that comes about that allows people using VirtualBox 5.0.x to use the boxes.

**Comment by jarofgreen** [comment] 2016-12-01 15:38
I tested V2.0.25 of boxcutter/ubuntu1604:

  *  Mac - VirtualBox 5.0.16 - broken.
  *  Linux - VirtualBox 4.1.44 - broken.

I tried adding the "--cableconnected1", "on", fix:

  *  Mac - VirtualBox 5.0.16 - works.
  *  Linux - VirtualBox 4.1.44 - Works.

So, at least there is a workaround.

But it's worth noting:

> people using VirtualBox 5.0.x to use the boxes

It's not just 5.0.x, it seems to be all pre 5.1.10. Which given all the Linux packaged versions, must be a lot. All Ubuntu versions are broken, for instance: http://packages.ubuntu.com/xenial/virtualbox

> so boxcutter will only build boxes with the latest 5.1.x guest additions

Not an expert on this, but Is there scope here to deliberately build boxes with an older version of VirtualBox? If we seem to be saying VB 5.1.6 was fine and then VB introduced a bug, wouldn't building against older versions make sense until the bug is fixed? 2.0.18 of the box works fine on my machines, so it's something about the builders version of VB not the users version. (Presumably parallels and vmware_desktop won't care what version of VB is used, so Atlas only allowing one version shouldn't be a problem.)

Anyway, thanks - I appreciate how frustrating it must be having a platform bug like this pop up :-(

**Comment by antwanvdm** [comment] 2016-12-06 10:42
I can confirm that my fix (https://github.com/boxcutter/ubuntu/issues/82#issuecomment-260902424) is no longer needed when working with virtualbox v5.1.10 & vagrant 1.9.0.

**Closed** 2016-12-09 07:22 UTC

**Comment by smebberson** [comment] 2016-12-13 23:26
@annawake, this is still an issue for me with VMware Fusion. Can we reopen this?

**Comment by jarofgreen** [comment] 2016-12-14 07:22
Can I just say, my personal view is that forcing users to upgrade to the latest VirtualBox isn't really a solution in my eyes. Some users won't want to or won't be able to. But if that's the line the project is taking I understand, thanks for discussing this.

**Comment by StefanScherer** [comment] 2016-12-14 13:57
Both `vagrant ssh` and `ssh -p 2211 vagrant@localhost` works fine for me with Fusion Pro 8.5.3, Vagrant 1.9.1 and boxcutter/ubuntu16.04 2.0.26. 👍
